config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :confession_queues do
    resources :schedulings, only: %i[index new create]
  end

  resources :schedulings, only: %i[edit update destroy]

  root to: 'confession_queues#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/confession_queue.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: confession_queues
#
#  id         :bigint           not null, primary key
#  city       :string           default(""), not null
#  date       :date
#  end_time   :datetime
#  latitude   :float
#  longitude  :float
#  notes      :text
#  place      :string
#  postcode   :string           default(""), not null
#  start_time :datetime
#  state      :string           default(""), not null
#  street     :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ConfessionQueue < ApplicationRecord
  has_many :schedulings

  validates :place, presence: true
  validates_date :date, on_or_after: Date.current,
                        on_or_after_message: "A data deve ser depois de #{Date.current}"
  validates_datetime :start_time, after: DateTime.current,
                                  after_message: "A hora de ínicio deve ser depois de #{Time.current}"
  validates_datetime :end_time, after: :start_time,
                                after_message: 'A hora de témino deve ser depois da hora de início'

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def address
    [street, city, postcode, state].compact.join(', ')
  end

  def address_changed?
    street_changed? || city_changed? || postcode_changed? || state_changed?
  end
end

app/models/scheduling.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: schedulings
#
#  id                  :bigint           not null, primary key
#  hour                :time
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  confession_queue_id :bigint           not null
#
# Indexes
#
#  index_schedulings_on_confession_queue_id  (confession_queue_id)
#
# Foreign Keys
#
#  fk_rails_...  (confession_queue_id => confession_queues.id)
#
class Scheduling < ApplicationRecord
  belongs_to :confession_queue

  validates :hour, uniqueness: { scope: :confession_queue_id,
                                 message: 'Este horário já foi selecionado por outra pessoa' }
  validates :hour, inclusion: { in: :valid_schedulings,
                                message: 'Horário inválido' }

  def valid_schedulings
    valid_schedulings = []
    confession_queue = ConfessionQueue.find(confession_queue_id)
    minute_step = confession_queue.start_time
    until valid_schedulings.include?(confession_queue.end_time.strftime('%R'))
      valid_schedulings << minute_step.strftime('%R')
      minute_step += 15.minutes
    end

    valid_schedulings
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/confession_queues_controller.rb
# frozen_string_literal: true

class ConfessionQueuesController < ApplicationController
  before_action :set_confession_queue, only: %i[show edit update destroy]

  def index
    @latlng = [-5.8415, -35.2104]
    @q = ConfessionQueue.ransack(params[:q])
    @confession_queues = @q.result.where('date >= ?', Date.today)
    if params[:q] && !params[:q]['date'].empty?
      @confession_queues = @q.result.where('date = ?',
                                           Date.parse(params[:q]['date']))
    end
  end

  def show; end

  def new
    @confession_queue = ConfessionQueue.new
  end

  def create
    @confession_queue = ConfessionQueue.new(confession_queue_params)
    sych_times unless @confession_queue.start_time.nil? || @confession_queue.end_time.nil?

    if @confession_queue.save
      redirect_to confession_queues_path
    else
      render :new
    end
  end

  def edit; end

  def update
    sych_times
    @confession_queue.update(confession_queue_params)

    redirect_to confession_queues_path
  end

  def destroy
    @confession_queue.destroy

    redirect_to confession_queues_path
  end

  private

  def sych_times
    @confession_queue.start_time = @confession_queue.start_time.change(year: confession_queue_params['date(1i)'].to_i,
                                                                       month: confession_queue_params['date(2i)'].to_i,
                                                                       day: confession_queue_params['date(3i)'].to_i)
    @confession_queue.end_time = @confession_queue.end_time.change(year: confession_queue_params['date(1i)'].to_i,
                                                                   month: confession_queue_params['date(2i)'].to_i,
                                                                   day: confession_queue_params['date(3i)'].to_i)
  end

  def set_confession_queue
    @confession_queue = ConfessionQueue.find(params[:id])
  end

  def confession_queue_params
    params.require(:confession_queue).permit(:date, :start_time, :end_time, :place, :notes, :street, :city, :state,
                                             :postcode)
  end
end

app/controllers/schedulings_controller.rb
# frozen_string_literal: true

class SchedulingsController < ApplicationController
  before_action :set_scheduling, only: %i[edit update destroy]
  before_action :set_confession_queue, only: %i[new create]

  def new
    @scheduling = Scheduling.new
    @scheduling_slots = scheduling_availability(@confession_queue)
  end

  def create
    @scheduling = Scheduling.new(scheduling_params)
    @scheduling.confession_queue = @confession_queue
    if @scheduling.save
      redirect_to confession_queues_path
    else
      @scheduling_slots = scheduling_availability(@confession_queue)
      render :new
    end
  end

  def edit
    @scheduling_slots = scheduling_availability(@scheduling.confession_queue)
  end

  def update
    @scheduling.update(scheduling_params)

    redirect_to confession_queues_path
  end

  def destroy
    @scheduling.destroy

    redirect_to confession_queues_path
  end

  private

  def set_scheduling
    @scheduling = Scheduling.find(params[:id])
  end

  def set_confession_queue
    @confession_queue = ConfessionQueue.find(params[:confession_queue_id])
  end

  def scheduling_availability(confession_queue)
    scheduling_availability = {}
    minute_step = confession_queue.start_time
    until scheduling_availability.keys.include?(confession_queue.end_time.strftime('%R'))
      scheduling_availability[minute_step.strftime('%R')] = !confession_queue.schedulings.map(&:hour)
                                                                             .include?(minute_step.strftime('%R'))
      minute_step += 15.minutes
    end

    scheduling_availability
  end

  def scheduling_params
    params.require(:scheduling).permit(:hour, :confession_queue_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/confession_queues_helper.rb
# frozen_string_literal: true

module ConfessionQueuesHelper
end

app/helpers/schedulings_helper.rb
# frozen_string_literal: true

module SchedulingsHelper
end

app/views/confession_queues/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 m-3">
      <%= form_with model: @confession_queue do |form| %>
        <div class="row">
          <div class="col-12 mb-3">
            <div class="col mb-2">
              <%= form.label :date, "Data" %>
            </div>
            <div class="col">
              <%= form.date_select :date, start_year:Date.today.year %>
            </div>
          </div>
          <div class="col-md-3 col-6 mb-3">
            <div class="col mb-2">
              <%= form.label :start_time, "Início" %>
            </div>
            <div class="col">
              <%= form.time_select :start_time, minute_step: 15 %>
            </div>
          </div>
          <div class="col-md-3 col-6 mb-3">
            <div class="col mb-2">
              <%= form.label :end_time, "Término" %>
            </div>
            <div class="col">
              <%= form.time_select :end_time, minute_step: 15 %>
            </div>
          </div>
          <div class="col-12 mb-3">
            <div class="col mb-2">
              <%= form.label :place, "Local" %>
            </div>
            <%= form.text_field :place, class:"form-control w-100" %>
          </div>
          <div class="col-12 mb-3">
            <div class="col mb-2">
              <%= form.label :notes, "Avisos" %>
            </div>
            <%= form.text_area :notes, class:"form-control w-100" %>
          </div>
          <div class="col-6">
            <%= form.submit "Editar", class:"btn btn-primary" %>
          </div>
          <div class="col-6 d-flex justify-content-end align-items-center">
            <%= link_to confession_queue_path(@confession_queue), method: :delete, data: { confirm: "Are you sure?" } do%>
              <i class="fas fa-trash-alt text-danger fs-3"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/confession_queues/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 p-3 text-end">
      <%= link_to new_confession_queue_path do%>
        <span class="btn btn-primary">Nova Fila</a>
      <% end %>
    </div>
    <div class="col-12 p-3 d-flex justify-content-center">
      <%= search_form_for @q, class: 'w-100 my-3' do |f|%>
        <div class="row justify-content-center">
          <div class="col-md-8 col-lg-4">
            <div class="col mb-2">
              <%= f.label :place, 'Cidade'%>
            </div>
            <div class="col mb-3">
              <%= f.search_field :city_cont, class: 'form-control col-md-6 w-100' %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="col mb-2">
              <%= f.label :date, 'Data' %>
            </div>
            <div class="col mb-3">
              <%= f.text_field :date,
                class: 'form-control text-center col-md-6',
                data: {
                  controller: "flatpickr",
                  flatpickr_date_format: "d/m/Y",
                  flatpickr_min_date: Time.zone.now
              } %>
            </div>
          </div>
          <div class="col-lg-1 ms-2 d-flex align-items-end justify-content-center mb-3">
            <%= f.submit "Pesquisar", class: 'btn btn-primary'%>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-lg-8">
      <% if params[:q] && params[:q].values.uniq != ['']  %>
       <h4>Resultados para '<%= "#{params[:q].values.reject{ |p| p == ''}.join(" ")}"%>'</h4>
      <% end %>
      <ul>
        <% @confession_queues.each do |confession_queue| %>
          <li>
            <%= link_to edit_confession_queue_path(confession_queue.id) do%>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %> |
            <%= confession_queue.place %> |
            <%= confession_queue.date.strftime('%d/%m/%Y') %> |
            Fila: <%= confession_queue.schedulings.count %> |
            <%= confession_queue.latitude ? Geocoder::Calculations.distance_between(@latlng, [confession_queue.latitude, confession_queue.longitude]).round(1) : "?" %> Km
            <%= link_to "Agendar", new_confession_queue_scheduling_path(confession_queue_id: confession_queue.id) %>
          </li>
            <% unless confession_queue.schedulings.empty? %>
              <ul>
                <% confession_queue.schedulings.sort_by{ |sch| sch.hour }.each do |scheduling| %>
                  <li>
                    <%= link_to edit_scheduling_path(scheduling.id) do%>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %> |
                    <%= scheduling.hour %>
                  </li>
                <% end %>
              </ul>
            <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/confession_queues/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 m-3">
      <%= form_with model: @confession_queue, authenticity_token: true do |form| %>
        <div class="row">
          <div class="col-12 mb-3">
            <div class="col mb-2">
              <%= form.label :date, "Data" %>
            </div>
            <div class="col">
              <%= form.date_select :date, start_year:Date.today.year %>
            </div>
          </div>
          <div class="col-md-3 col-6 mb-3">
            <div class="col mb-2">
              <%= form.label :start_time, "Início" %>
            </div>
            <div class="col">
              <%= form.time_select :start_time, minute_step: 15 %>
            </div>
          </div>
          <div class="col-md-3 col-6 mb-3">
            <div class="col mb-2">
              <%= form.label :end_time, "Término" %>
            </div>
            <div class="col">
              <%= form.time_select :end_time, minute_step: 15 %>
            </div>
          </div>
          <div class="col-12 mb-3">
            <div class="col mb-2">
              <%= form.label :place, "Local" %>
            </div>
            <%= form.text_field :place, class:"form-control w-100" %>
          </div>
          <div class="col-9 mb-3">
            <div class="col mb-2">
              <%= form.label :street, "Rua" %>
            </div>
            <%= form.text_field :street, class:"form-control w-100" %>
          </div>
          <div class="col-md-4 mb-3">
            <div class="col mb-2">
              <%= form.label :city, "Cidade" %>
            </div>
            <%= form.text_field :city, class:"form-control w-100" %>
          </div>
          <div class="col-md-4 mb-3">
            <div class="col mb-2">
              <%= form.label :state, "Estado" %>
            </div>
            <%= form.text_field :state, class:"form-control w-100" %>
          </div>
          <div class="col-md-4 mb-3">
            <div class="col mb-2">
              <%= form.label :postcode, "CEP" %>
            </div>
            <%= form.text_field :postcode, class:"form-control w-100" %>
          </div>
          <div class="col-12 mb-3">
            <div class="col mb-2">
              <%= form.label :notes, "Avisos" %>
            </div>
            <%= form.text_area :notes, class:"form-control w-100" %>
          </div>
          <div class="col-12">
            <%= form.submit "Cadastrar", class:"btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miserere</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script src="https://kit.fontawesome.com/4cf9bf5d09.js" crossorigin="anonymous"></script>
</html>

app/views/schedulings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 m-3">
      <%= form_with(model: [@scheduling]) do |form| %>
        <% @scheduling_slots.keys.each do |slot| %>
          <% if @scheduling_slots[slot] %>
            <%= form.radio_button :hour, "#{slot}", class:'d-none'%>
            <%= form.label "hour_#{slot.gsub(':','')}", "#{slot}", class:'btn btn-sm btn-outline-primary mx-1'%>
          <% else %>
            <%= form.radio_button :hour, "#{slot}", disabled: true, class:'d-none'%>
            <%= form.label "hour_#{slot.gsub(':','')}", "#{slot}", class:'btn btn-sm disabled btn-outline-secondary text-decoration-line-through mx-1'%>
          <% end %>
        <% end %>
        <%= form.submit "Editar", class:"btn btn-primary" %>
      <% end %>
      <%= link_to scheduling_path(@scheduling), method: :delete, data: { confirm: "Are you sure?" } do%>
        <i class="fas fa-trash-alt text-danger fs-3"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/schedulings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 m-3">
      <%= form_with(model: [@confession_queue, @scheduling]) do |form| %>
        <% @scheduling_slots.keys.each do |slot| %>
          <% if @scheduling_slots[slot] %>
            <%= form.radio_button :hour, "#{slot}"%>
            <%= form.label "hour_#{slot.gsub(':','')}", "#{slot}", class:'btn btn-sm btn-outline-primary'%>
          <% else %>
            <%= form.radio_button :hour, "#{slot}", disabled: true%>
            <%= form.label "hour_#{slot.gsub(':','')}", "#{slot}", class:'btn btn-sm disabled btn-outline-secondary'%>
          <% end %>
        <% end %>

        <%= form.submit "Cadastrar", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>